### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by sjagoe**
Small changes to allow Python 2 and Python 3 support through `2to3`.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks for looking at this. These days we (ipython, pyzmq, sympy, etc) are trying to run on Python 2 and 3 using a single code base using tools like six and other wrappers. Here are some notes about how we are doing this for ipython:

http://ipython.org/ipython-doc/dev/development/pycompat.html

Do you think you could see if you could get this approach working?

**Comment by sjagoe** [comment]
Sure, I'll have some time to take a look this evening. I tend to prefer that approach as well, but needed something in the shortest time possible :-)

**Comment by ellisonbg** [comment]
OK great, let me know how it goes. If you can't get to it quickly, I can
always merge your current PR and go the other stuff longer term.

On Fri, Apr 11, 2014 at 10:32 AM, Simon Jagoe notifications@github.comwrote:

> Sure, I'll have some time to take a look this evening. I tend to prefer
> that approach as well, but needed something in the shortest time possible
> :-)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ellisonbg/zpyrpc/pull/2#issuecomment-40228954
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sjagoe** [comment]
@ellisonbg With my last commit this now works for Python 2 and Python 3 from the same source.

**Comment by ellisonbg** [comment]
Great!

**Pull request merged**
